/home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/S_trainer.py --dataset_class PCB_200 --data_path ./My_TAOD/dataset/PCB_200/0.7-shot/train/0.csv --catagory 0 --gpu_id "0" --num_epochs 500
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/S_trainer.py --dataset_class PCB_200 --data_path ./My_TAOD/dataset/PCB_200/0.7-shot/train/1.csv --catagory 1 --gpu_id "1"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/S_trainer.py --dataset_class PCB_200 --data_path ./My_TAOD/dataset/PCB_200/0.7-shot/train/2.csv --catagory 2 --gpu_id "1"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/S_trainer.py --dataset_class PCB_200 --data_path ./My_TAOD/dataset/PCB_200/0.7-shot/train/3.csv --catagory 3 --gpu_id "1"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/S_trainer.py --dataset_class PCB_200 --data_path ./My_TAOD/dataset/PCB_200/0.7-shot/train/4.csv --catagory 4 --gpu_id "1"

# /home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/S_trainer.py --dataset_class PCB_Crop --data_path ./My_TAOD/dataset/PCB_Crop/0.7-shot/train/0.csv --catagory 0 --gpu_id "1"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/S_trainer.py --dataset_class PCB_Crop --data_path ./My_TAOD/dataset/PCB_Crop/0.7-shot/train/1.csv --catagory 1 --gpu_id "1"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/S_trainer.py --dataset_class PCB_Crop --data_path ./My_TAOD/dataset/PCB_Crop/0.7-shot/train/2.csv --catagory 2 --gpu_id "1"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/S_trainer.py --dataset_class PCB_Crop --data_path ./My_TAOD/dataset/PCB_Crop/0.7-shot/train/3.csv --catagory 3 --gpu_id "1"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/S_trainer.py --dataset_class PCB_Crop --data_path ./My_TAOD/dataset/PCB_Crop/0.7-shot/train/4.csv --catagory 4 --gpu_id "1"
