# train 30-shot
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "30-shot" --classification_net "Resnet18_Pretrained"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "30-shot" --classification_net "Resnet50_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "30-shot" --classification_net "EfficientNet_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "30-shot" --classification_net "VGG11_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "30-shot" --classification_net "MobileNet_Pretrained" 

# test 30-shot
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "30-shot" --classification_net "Resnet18_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/DeepPCB_Crop Resnet18_Pretrained 20241127_210917/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "30-shot" --classification_net "Resnet50_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/DeepPCB_Crop Resnet50_Pretrained 20241127_211056/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "30-shot" --classification_net "EfficientNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/DeepPCB_Crop EfficientNet_Pretrained 20241220_173601/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "30-shot" --classification_net "VGG11_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/DeepPCB_Crop VGG11_Pretrained 20241220_184005/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "30-shot" --classification_net "MobileNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/DeepPCB_Crop MobileNet_Pretrained 20241220_184207/models/100.pth"

# train 10-shot
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "Resnet18_Pretrained"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "Resnet50_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "EfficientNet_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "VGG11_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "MobileNet_Pretrained" 

# test 10-shot
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "Resnet18_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/DeepPCB_Crop Resnet18_Pretrained 20241127_211724/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "Resnet50_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/DeepPCB_Crop Resnet50_Pretrained 20241127_211846/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "EfficientNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/DeepPCB_Crop EfficientNet_Pretrained 20241220_173930/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "VGG11_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/DeepPCB_Crop VGG11_Pretrained 20241220_184402/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "MobileNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/DeepPCB_Crop MobileNet_Pretrained 20241220_184548/models/100.pth"