#* single-domain

# train 30-shot
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "30-shot" --classification_net "Resnet18_Pretrained"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "30-shot" --classification_net "Resnet50_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "30-shot" --classification_net "EfficientNet_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "30-shot" --classification_net "VGG11_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "30-shot" --classification_net "MobileNet_Pretrained" 
# test 30-shot
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "30-shot" --classification_net "Resnet18_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop Resnet18_Pretrained 20241127_211105/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "30-shot" --classification_net "Resnet50_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop Resnet50_Pretrained 20241127_211240/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "30-shot" --classification_net "EfficientNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop EfficientNet_Pretrained 20241220_173615/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "30-shot" --classification_net "VGG11_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop VGG11_Pretrained 20241220_184334/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "30-shot" --classification_net "MobileNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop MobileNet_Pretrained 20241220_184553/models/100.pth"

# train 10-shot
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "Resnet18_Pretrained"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "Resnet50_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "EfficientNet_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "VGG11_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "MobileNet_Pretrained" 
# test 10-shot
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "Resnet18_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop Resnet18_Pretrained 20241127_211855/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "Resnet50_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop Resnet50_Pretrained 20241127_212014/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "EfficientNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop EfficientNet_Pretrained 20241220_173943/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "VGG11_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop VGG11_Pretrained 20241220_184749/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "MobileNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop MobileNet_Pretrained 20241220_185143/models/100.pth"

# train 160-shot
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "160-shot" --classification_net "Resnet18_Pretrained"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "160-shot" --classification_net "Resnet50_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "160-shot" --classification_net "EfficientNet_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "160-shot" --classification_net "VGG11_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "160-shot" --classification_net "MobileNet_Pretrained" 
# test 160-shot
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "160-shot" --classification_net "Resnet18_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop Resnet18_Pretrained 20241225_154616/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "160-shot" --classification_net "Resnet50_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop Resnet50_Pretrained 20241225_154910/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "160-shot" --classification_net "EfficientNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop EfficientNet_Pretrained 20241225_155417/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "160-shot" --classification_net "VGG11_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop VGG11_Pretrained 20241225_160032/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "160-shot" --classification_net "MobileNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop MobileNet_Pretrained 20241225_160558/models/100.pth"
