#* fintuning
# fintuning: DPC(160-shot) -> P2(10-shot)
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "0" --dataset_ratio "10-shot" --classification_net "Resnet18_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/DeepPCB_Crop Resnet18_Pretrained 20241225_154419/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "0" --dataset_ratio "10-shot" --classification_net "Resnet50_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/DeepPCB_Crop Resnet50_Pretrained 20241225_154713/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "0" --dataset_ratio "10-shot" --classification_net "EfficientNet_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/DeepPCB_Crop EfficientNet_Pretrained 20241225_155208/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "0" --dataset_ratio "10-shot" --classification_net "VGG11_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/DeepPCB_Crop VGG11_Pretrained 20241225_155816/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "0" --dataset_ratio "10-shot" --classification_net "MobileNet_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/DeepPCB_Crop MobileNet_Pretrained 20241225_160208/models/100.pth"

# fintuning: PC(160-shot) -> P2(10-shot)
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "0" --dataset_ratio "10-shot" --classification_net "Resnet18_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop Resnet18_Pretrained 20241225_154616/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "0" --dataset_ratio "10-shot" --classification_net "Resnet50_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop Resnet50_Pretrained 20241225_154910/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "0" --dataset_ratio "10-shot" --classification_net "EfficientNet_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop EfficientNet_Pretrained 20241225_155417/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "0" --dataset_ratio "10-shot" --classification_net "VGG11_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop VGG11_Pretrained 20241225_160032/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "0" --dataset_ratio "10-shot" --classification_net "MobileNet_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop MobileNet_Pretrained 20241225_160558/models/100.pth"
