#* fintuning

# fintuning: P2(160-shot) -> DPC(10-shot)
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "Resnet18_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_200 Resnet18_Pretrained 20241225_154528/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "Resnet50_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_200 Resnet50_Pretrained 20241225_154820/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "EfficientNet_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_200 EfficientNet_Pretrained 20241225_155325/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "VGG11_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_200 VGG11_Pretrained 20241225_155942/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "MobileNet_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_200 MobileNet_Pretrained 20241225_160513/models/100.pth"
# test: P2(160-shot) -> DPC(10-shot)
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "Resnet18_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/finetuning/DeepPCB_Crop Resnet18_Pretrained 20241225_182845/models/50.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "Resnet50_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/finetuning/DeepPCB_Crop Resnet50_Pretrained 20241225_183029/models/50.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "EfficientNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/finetuning/DeepPCB_Crop EfficientNet_Pretrained 20241225_183223/models/50.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "VGG11_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/finetuning/DeepPCB_Crop VGG11_Pretrained 20241225_183412/models/50.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "MobileNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/finetuning/DeepPCB_Crop MobileNet_Pretrained 20241225_183618/models/50.pth"

# fintuning: PC(160-shot) -> DPC(10-shot)
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "Resnet18_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop Resnet18_Pretrained 20241225_154616/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "Resnet50_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop Resnet50_Pretrained 20241225_154910/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "EfficientNet_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop EfficientNet_Pretrained 20241225_155417/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "VGG11_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop VGG11_Pretrained 20241225_160032/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "MobileNet_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_Crop MobileNet_Pretrained 20241225_160558/models/100.pth"
# test: PC(160-shot) -> DPC(10-shot)
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "Resnet18_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/finetuning/DeepPCB_Crop Resnet18_Pretrained 20241225_183804/models/50.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "Resnet50_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/finetuning/DeepPCB_Crop Resnet50_Pretrained 20241225_183941/models/50.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "EfficientNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/finetuning/DeepPCB_Crop EfficientNet_Pretrained 20241225_184116/models/50.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "VGG11_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/finetuning/DeepPCB_Crop VGG11_Pretrained 20241225_184251/models/50.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot" --classification_net "MobileNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/finetuning/DeepPCB_Crop MobileNet_Pretrained 20241225_184443/models/50.pth"
