#* fintuning

# fintuning: DPC(160-shot) -> PC(10-shot)
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "Resnet18_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/DeepPCB_Crop Resnet18_Pretrained 20241225_154419/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "Resnet50_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/DeepPCB_Crop Resnet50_Pretrained 20241225_154713/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "EfficientNet_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/DeepPCB_Crop EfficientNet_Pretrained 20241225_155208/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "VGG11_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/DeepPCB_Crop VGG11_Pretrained 20241225_155816/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "MobileNet_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/DeepPCB_Crop MobileNet_Pretrained 20241225_160208/models/100.pth"
# test: DPC(160-shot) -> PC(10-shot)
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "Resnet18_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/finetuning/PCB_Crop Resnet18_Pretrained 20241225_182921/models/50.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "Resnet50_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/finetuning/PCB_Crop Resnet50_Pretrained 20241225_183055/models/50.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "EfficientNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/finetuning/PCB_Crop EfficientNet_Pretrained 20241225_183236/models/50.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "VGG11_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/finetuning/PCB_Crop VGG11_Pretrained 20241225_183418/models/50.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "MobileNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/finetuning/PCB_Crop MobileNet_Pretrained 20241225_183617/models/50.pth"

# fintuning: P2(160-shot) -> PC(10-shot)
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "Resnet18_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_200 Resnet18_Pretrained 20241225_154528/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "Resnet50_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_200 Resnet50_Pretrained 20241225_154820/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "EfficientNet_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_200 EfficientNet_Pretrained 20241225_155325/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "VGG11_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_200 VGG11_Pretrained 20241225_155942/models/100.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "MobileNet_Pretrained" --model_init_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/cls_single_domain/PCB_200 MobileNet_Pretrained 20241225_160513/models/100.pth"
# test: P2(160-shot) -> PC(10-shot)
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "Resnet18_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/finetuning/PCB_Crop Resnet18_Pretrained 20241225_183803/models/50.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "Resnet50_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/finetuning/PCB_Crop Resnet50_Pretrained 20241225_183930/models/50.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "EfficientNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/finetuning/PCB_Crop EfficientNet_Pretrained 20241225_184058/models/50.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "VGG11_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/finetuning/PCB_Crop VGG11_Pretrained 20241225_184230/models/50.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "1" --dataset_ratio "10-shot" --classification_net "MobileNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/finetuning/PCB_Crop MobileNet_Pretrained 20241225_184414/models/50.pth"
