#* P2(10) + DPC(150)

# train
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "1" --dataset_ratio "10-shot + DeepPCB_Crop(150)" --classification_net "Resnet18_Pretrained"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "1" --dataset_ratio "10-shot + DeepPCB_Crop(150)" --classification_net "Resnet50_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "1" --dataset_ratio "10-shot + DeepPCB_Crop(150)" --classification_net "EfficientNet_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "1" --dataset_ratio "10-shot + DeepPCB_Crop(150)" --classification_net "VGG11_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "1" --dataset_ratio "10-shot + DeepPCB_Crop(150)" --classification_net "MobileNet_Pretrained" 
# test
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_200 --gpu_id "1" --dataset_ratio "10-shot + DeepPCB_Crop(150)" --classification_net "Resnet18_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/PCB_200 Resnet18_Pretrained 20241226_163501/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_200 --gpu_id "1" --dataset_ratio "10-shot + DeepPCB_Crop(150)" --classification_net "Resnet50_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/PCB_200 Resnet50_Pretrained 20241226_163748/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_200 --gpu_id "1" --dataset_ratio "10-shot + DeepPCB_Crop(150)" --classification_net "EfficientNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/PCB_200 EfficientNet_Pretrained 20241226_164237/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_200 --gpu_id "1" --dataset_ratio "10-shot + DeepPCB_Crop(150)" --classification_net "VGG11_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/PCB_200 VGG11_Pretrained 20241226_164833/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_200 --gpu_id "1" --dataset_ratio "10-shot + DeepPCB_Crop(150)" --classification_net "MobileNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/PCB_200 MobileNet_Pretrained 20241226_165217/models/100.pth"

#* P2(10) + PC(150)

# train
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "1" --dataset_ratio "10-shot + PCB_Crop(150)" --classification_net "Resnet18_Pretrained"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "1" --dataset_ratio "10-shot + PCB_Crop(150)" --classification_net "Resnet50_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "1" --dataset_ratio "10-shot + PCB_Crop(150)" --classification_net "EfficientNet_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "1" --dataset_ratio "10-shot + PCB_Crop(150)" --classification_net "VGG11_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "1" --dataset_ratio "10-shot + PCB_Crop(150)" --classification_net "MobileNet_Pretrained" 
# test
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_200 --gpu_id "1" --dataset_ratio "10-shot + PCB_Crop(150)" --classification_net "Resnet18_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/PCB_200 Resnet18_Pretrained 20241226_165632/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_200 --gpu_id "1" --dataset_ratio "10-shot + PCB_Crop(150)" --classification_net "Resnet50_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/PCB_200 Resnet50_Pretrained 20241226_165916/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_200 --gpu_id "1" --dataset_ratio "10-shot + PCB_Crop(150)" --classification_net "EfficientNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/PCB_200 EfficientNet_Pretrained 20241226_170403/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_200 --gpu_id "1" --dataset_ratio "10-shot + PCB_Crop(150)" --classification_net "VGG11_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/PCB_200 VGG11_Pretrained 20241226_171008/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_200 --gpu_id "1" --dataset_ratio "10-shot + PCB_Crop(150)" --classification_net "MobileNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/PCB_200 MobileNet_Pretrained 20241226_171348/models/100.pth"
