#* DPC(10) + P2(150)

# train
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_200(150)" --classification_net "Resnet18_Pretrained"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_200(150)" --classification_net "Resnet50_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_200(150)" --classification_net "EfficientNet_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_200(150)" --classification_net "VGG11_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_200(150)" --classification_net "MobileNet_Pretrained" 
# test
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_200(150)" --classification_net "Resnet18_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/DeepPCB_Crop Resnet18_Pretrained 20241226_163458/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_200(150)" --classification_net "Resnet50_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/DeepPCB_Crop Resnet50_Pretrained 20241226_163749/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_200(150)" --classification_net "EfficientNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/DeepPCB_Crop EfficientNet_Pretrained 20241226_164255/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_200(150)" --classification_net "VGG11_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/DeepPCB_Crop VGG11_Pretrained 20241226_164853/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_200(150)" --classification_net "MobileNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/DeepPCB_Crop MobileNet_Pretrained 20241226_165416/models/100.pth"

#* DPC(10) + PC(150)

# train
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_Crop(150)" --classification_net "Resnet18_Pretrained"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_Crop(150)" --classification_net "Resnet50_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_Crop(150)" --classification_net "EfficientNet_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_Crop(150)" --classification_net "VGG11_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_Crop(150)" --classification_net "MobileNet_Pretrained" 
# test
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_Crop(150)" --classification_net "Resnet18_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/DeepPCB_Crop Resnet18_Pretrained 20241226_165836/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_Crop(150)" --classification_net "Resnet50_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/DeepPCB_Crop Resnet50_Pretrained 20241226_170125/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_Crop(150)" --classification_net "EfficientNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/DeepPCB_Crop EfficientNet_Pretrained 20241226_170629/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_Crop(150)" --classification_net "VGG11_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/DeepPCB_Crop VGG11_Pretrained 20241226_171227/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_Crop(150)" --classification_net "MobileNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/DeepPCB_Crop MobileNet_Pretrained 20241226_171755/models/100.pth"
