#* PC(10) + DPC(150)

# train
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "0" --dataset_ratio "10-shot + DeepPCB_Crop(150)" --classification_net "Resnet18_Pretrained"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "0" --dataset_ratio "10-shot + DeepPCB_Crop(150)" --classification_net "Resnet50_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "0" --dataset_ratio "10-shot + DeepPCB_Crop(150)" --classification_net "EfficientNet_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "0" --dataset_ratio "10-shot + DeepPCB_Crop(150)" --classification_net "VGG11_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "0" --dataset_ratio "10-shot + DeepPCB_Crop(150)" --classification_net "MobileNet_Pretrained" 
# test
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "0" --dataset_ratio "10-shot + DeepPCB_Crop(150)" --classification_net "Resnet18_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/PCB_Crop Resnet18_Pretrained 20241226_163503/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "0" --dataset_ratio "10-shot + DeepPCB_Crop(150)" --classification_net "Resnet50_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/PCB_Crop Resnet50_Pretrained 20241226_163759/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "0" --dataset_ratio "10-shot + DeepPCB_Crop(150)" --classification_net "EfficientNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/PCB_Crop EfficientNet_Pretrained 20241226_164306/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "0" --dataset_ratio "10-shot + DeepPCB_Crop(150)" --classification_net "VGG11_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/PCB_Crop VGG11_Pretrained 20241226_164914/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "0" --dataset_ratio "10-shot + DeepPCB_Crop(150)" --classification_net "MobileNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/PCB_Crop MobileNet_Pretrained 20241226_165438/models/100.pth"

#* PC(10) + P2(150)

# train
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_200(150)" --classification_net "Resnet18_Pretrained"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_200(150)" --classification_net "Resnet50_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_200(150)" --classification_net "EfficientNet_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_200(150)" --classification_net "VGG11_Pretrained" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_200(150)" --classification_net "MobileNet_Pretrained" 
# test
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_200(150)" --classification_net "Resnet18_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/PCB_Crop Resnet18_Pretrained 20241226_165858/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_200(150)" --classification_net "Resnet50_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/PCB_Crop Resnet50_Pretrained 20241226_170150/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_200(150)" --classification_net "EfficientNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/PCB_Crop EfficientNet_Pretrained 20241226_170700/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_200(150)" --classification_net "VGG11_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/PCB_Crop VGG11_Pretrained 20241226_171311/models/100.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "0" --dataset_ratio "10-shot + PCB_200(150)" --classification_net "MobileNet_Pretrained" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/results/train/mix_origin_sample/PCB_Crop MobileNet_Pretrained 20241226_171840/models/100.pth"
