# 10-shot
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/TA_Models/CoGAN/trainer.py --Tar_dataset_path "My_TAOD/dataset/DeepPCB_Crop/10-shot/train/0.csv" --Src_dataset_path "My_TAOD/dataset/PCB_Crop/200-shot/train/0.csv" --gpu_id "1"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/TA_Models/CoGAN/trainer.py --Tar_dataset_path "My_TAOD/dataset/DeepPCB_Crop/10-shot/train/1.csv" --Src_dataset_path "My_TAOD/dataset/PCB_Crop/200-shot/train/1.csv" --gpu_id "1"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/TA_Models/CoGAN/trainer.py --Tar_dataset_path "My_TAOD/dataset/DeepPCB_Crop/10-shot/train/2.csv" --Src_dataset_path "My_TAOD/dataset/PCB_Crop/200-shot/train/2.csv" --gpu_id "1"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/TA_Models/CoGAN/trainer.py --Tar_dataset_path "My_TAOD/dataset/DeepPCB_Crop/10-shot/train/3.csv" --Src_dataset_path "My_TAOD/dataset/PCB_Crop/200-shot/train/3.csv" --gpu_id "1"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/TA_Models/CoGAN/trainer.py --Tar_dataset_path "My_TAOD/dataset/DeepPCB_Crop/10-shot/train/4.csv" --Src_dataset_path "My_TAOD/dataset/PCB_Crop/200-shot/train/4.csv" --gpu_id "1"

# /home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/TA_Models/CoGAN/trainer.py --Tar_dataset_path "My_TAOD/dataset/PCB_Crop/10-shot/train/0.csv" --Src_dataset_path "My_TAOD/dataset/DeepPCB_Crop/200-shot/train/0.csv" --gpu_id "1"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/TA_Models/CoGAN/trainer.py --Tar_dataset_path "My_TAOD/dataset/PCB_Crop/10-shot/train/1.csv" --Src_dataset_path "My_TAOD/dataset/DeepPCB_Crop/200-shot/train/1.csv" --gpu_id "1"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/TA_Models/CoGAN/trainer.py --Tar_dataset_path "My_TAOD/dataset/PCB_Crop/10-shot/train/2.csv" --Src_dataset_path "My_TAOD/dataset/DeepPCB_Crop/200-shot/train/2.csv" --gpu_id "1"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/TA_Models/CoGAN/trainer.py --Tar_dataset_path "My_TAOD/dataset/PCB_Crop/10-shot/train/3.csv" --Src_dataset_path "My_TAOD/dataset/DeepPCB_Crop/200-shot/train/3.csv" --gpu_id "1"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/TA_Models/CoGAN/trainer.py --Tar_dataset_path "My_TAOD/dataset/PCB_Crop/10-shot/train/4.csv" --Src_dataset_path "My_TAOD/dataset/DeepPCB_Crop/200-shot/train/4.csv" --gpu_id "1"

# 30-shot
/home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/TA_Models/CoGAN/trainer.py --Tar_dataset_path "My_TAOD/dataset/DeepPCB_Crop/30-shot/train/0.csv" --Src_dataset_path "My_TAOD/dataset/PCB_Crop/200-shot/train/0.csv" --gpu_id "1"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/TA_Models/CoGAN/trainer.py --Tar_dataset_path "My_TAOD/dataset/DeepPCB_Crop/30-shot/train/1.csv" --Src_dataset_path "My_TAOD/dataset/PCB_Crop/200-shot/train/1.csv" --gpu_id "1"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/TA_Models/CoGAN/trainer.py --Tar_dataset_path "My_TAOD/dataset/DeepPCB_Crop/30-shot/train/2.csv" --Src_dataset_path "My_TAOD/dataset/PCB_Crop/200-shot/train/2.csv" --gpu_id "1"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/TA_Models/CoGAN/trainer.py --Tar_dataset_path "My_TAOD/dataset/DeepPCB_Crop/30-shot/train/3.csv" --Src_dataset_path "My_TAOD/dataset/PCB_Crop/200-shot/train/3.csv" --gpu_id "1"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/TA_Models/CoGAN/trainer.py --Tar_dataset_path "My_TAOD/dataset/DeepPCB_Crop/30-shot/train/4.csv" --Src_dataset_path "My_TAOD/dataset/PCB_Crop/200-shot/train/4.csv" --gpu_id "1"

/home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/TA_Models/CoGAN/trainer.py --Tar_dataset_path "My_TAOD/dataset/PCB_Crop/30-shot/train/0.csv" --Src_dataset_path "My_TAOD/dataset/DeepPCB_Crop/200-shot/train/0.csv" --gpu_id "1"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/TA_Models/CoGAN/trainer.py --Tar_dataset_path "My_TAOD/dataset/PCB_Crop/30-shot/train/1.csv" --Src_dataset_path "My_TAOD/dataset/DeepPCB_Crop/200-shot/train/1.csv" --gpu_id "1"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/TA_Models/CoGAN/trainer.py --Tar_dataset_path "My_TAOD/dataset/PCB_Crop/30-shot/train/2.csv" --Src_dataset_path "My_TAOD/dataset/DeepPCB_Crop/200-shot/train/2.csv" --gpu_id "1"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/TA_Models/CoGAN/trainer.py --Tar_dataset_path "My_TAOD/dataset/PCB_Crop/30-shot/train/3.csv" --Src_dataset_path "My_TAOD/dataset/DeepPCB_Crop/200-shot/train/3.csv" --gpu_id "1"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python /home/zhouquan/MyDoc/Deep_Learning/My_TAOD/TA/TA_Models/CoGAN/trainer.py --Tar_dataset_path "My_TAOD/dataset/PCB_Crop/30-shot/train/4.csv" --Src_dataset_path "My_TAOD/dataset/DeepPCB_Crop/200-shot/train/4.csv" --gpu_id "1"
