# train
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "0" --dataset_train_dir "My_TAOD/dataset/PCB_200/30-shot/train.csv" --classification_net "VGG11" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "0" --dataset_train_dir "My_TAOD/dataset/PCB_200/30-shot/train.csv" --classification_net "Resnet18"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "0" --dataset_train_dir "My_TAOD/dataset/PCB_200/30-shot/train.csv" --classification_net "Resnet50"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "0" --dataset_train_dir "My_TAOD/dataset/PCB_200/30-shot/train.csv" --classification_net "Resnet18_Pretrained"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_200 --gpu_id "0" --dataset_train_dir "My_TAOD/dataset/PCB_200/30-shot/train.csv" --classification_net "Resnet50_Pretrained" 

# test
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_200 --gpu_id "0"  --dataset_test_dir "My_TAOD/dataset/PCB_200/30-shot/test.csv" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/models/PCB_200 VGG11 20240420_182057/200.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_200 --gpu_id "0"  --dataset_test_dir "My_TAOD/dataset/PCB_200/30-shot/test.csv" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/models/PCB_200 Resnet18 20240420_182339/200.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_200 --gpu_id "0"  --dataset_test_dir "My_TAOD/dataset/PCB_200/30-shot/test.csv" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/models/PCB_200 Resnet50 20240420_182625/200.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_200 --gpu_id "0"  --dataset_test_dir "My_TAOD/dataset/PCB_200/30-shot/test.csv" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/models/PCB_200 Resnet18_Pretrained 20240420_182955/200.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_200 --gpu_id "0"  --dataset_test_dir "My_TAOD/dataset/PCB_200/30-shot/test.csv" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/models/PCB_200 Resnet50_Pretrained 20240420_183236/200.pth"