# train 30-shot
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "1" --dataset_train_dir "My_TAOD/dataset/DeepPCB_Crop/30-shot/train.csv" --classification_net "VGG11" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "1" --dataset_train_dir "My_TAOD/dataset/DeepPCB_Crop/30-shot/train.csv" --classification_net "Resnet18"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "1" --dataset_train_dir "My_TAOD/dataset/DeepPCB_Crop/30-shot/train.csv" --classification_net "Resnet50"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "1" --dataset_train_dir "My_TAOD/dataset/DeepPCB_Crop/30-shot/train.csv" --classification_net "Resnet18_Pretrained"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "1" --dataset_train_dir "My_TAOD/dataset/DeepPCB_Crop/30-shot/train.csv" --classification_net "Resnet50_Pretrained" 

# test 30-shot
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "1"  --dataset_test_dir "My_TAOD/dataset/DeepPCB_Crop/30-shot/test.csv" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/models/DeepPCB_Crop VGG11 20240420_182249/200.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "1"  --dataset_test_dir "My_TAOD/dataset/DeepPCB_Crop/30-shot/test.csv" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/models/DeepPCB_Crop Resnet18 20240420_182544/200.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "1"  --dataset_test_dir "My_TAOD/dataset/DeepPCB_Crop/30-shot/test.csv" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/models/DeepPCB_Crop Resnet50 20240420_182820/200.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "1"  --dataset_test_dir "My_TAOD/dataset/DeepPCB_Crop/30-shot/test.csv" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/models/DeepPCB_Crop Resnet18_Pretrained 20240420_183147/200.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "1"  --dataset_test_dir "My_TAOD/dataset/DeepPCB_Crop/30-shot/test.csv" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/models/DeepPCB_Crop Resnet50_Pretrained 20240420_183427/200.pth"

# train 10-shot
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "1" --dataset_train_dir "My_TAOD/dataset/DeepPCB_Crop/10-shot/train.csv" --classification_net "VGG11" 
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "1" --dataset_train_dir "My_TAOD/dataset/DeepPCB_Crop/10-shot/train.csv" --classification_net "Resnet18"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "1" --dataset_train_dir "My_TAOD/dataset/DeepPCB_Crop/10-shot/train.csv" --classification_net "Resnet50"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "1" --dataset_train_dir "My_TAOD/dataset/DeepPCB_Crop/10-shot/train.csv" --classification_net "Resnet18_Pretrained"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class DeepPCB_Crop --gpu_id "1" --dataset_train_dir "My_TAOD/dataset/DeepPCB_Crop/10-shot/train.csv" --classification_net "Resnet50_Pretrained" 

# test 10-shot
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "1"  --dataset_test_dir "My_TAOD/dataset/DeepPCB_Crop/10-shot/test.csv" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/models/DeepPCB_Crop VGG11 20240420_182249/200.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "1"  --dataset_test_dir "My_TAOD/dataset/DeepPCB_Crop/10-shot/test.csv" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/models/DeepPCB_Crop Resnet18 20240420_182544/200.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "1"  --dataset_test_dir "My_TAOD/dataset/DeepPCB_Crop/10-shot/test.csv" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/models/DeepPCB_Crop Resnet50 20240420_182820/200.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "1"  --dataset_test_dir "My_TAOD/dataset/DeepPCB_Crop/10-shot/test.csv" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/models/DeepPCB_Crop Resnet18_Pretrained 20240420_183147/200.pth"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class DeepPCB_Crop --gpu_id "1"  --dataset_test_dir "My_TAOD/dataset/DeepPCB_Crop/10-shot/test.csv" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/models/DeepPCB_Crop Resnet50_Pretrained 20240420_183427/200.pth"

