# train
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "0" --dataset_train_dir "My_TAOD/dataset/PCB_Crop/30-shot/train.csv" --classification_net "VGG11" 
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "0" --dataset_train_dir "My_TAOD/dataset/PCB_Crop/30-shot/train.csv" --classification_net "Resnet18"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "0" --dataset_train_dir "My_TAOD/dataset/PCB_Crop/30-shot/train.csv" --classification_net "Resnet50"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "0" --dataset_train_dir "My_TAOD/dataset/PCB_Crop/30-shot/train.csv" --classification_net "Resnet18_Pretrained"
# /home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode train --dataset_class PCB_Crop --gpu_id "0" --dataset_train_dir "My_TAOD/dataset/PCB_Crop/30-shot/train.csv" --classification_net "Resnet50_Pretrained" 

# test
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "0"  --dataset_test_dir "My_TAOD/dataset/PCB_Crop/30-shot/test.csv" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/models/PCB_Crop VGG11 20240420_182230/200.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "0"  --dataset_test_dir "My_TAOD/dataset/PCB_Crop/30-shot/test.csv" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/models/PCB_Crop Resnet18 20240420_182518/200.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "0"  --dataset_test_dir "My_TAOD/dataset/PCB_Crop/30-shot/test.csv" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/models/PCB_Crop Resnet50 20240420_182757/200.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "0"  --dataset_test_dir "My_TAOD/dataset/PCB_Crop/30-shot/test.csv" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/models/PCB_Crop Resnet18_Pretrained 20240420_183125/200.pth"
/home/zhouquan/anaconda3/envs/DLstudy/bin/python My_TAOD/Train_Classification/main.py --mode test --dataset_class PCB_Crop --gpu_id "0"  --dataset_test_dir "My_TAOD/dataset/PCB_Crop/30-shot/test.csv" --test_model_path "/home/zhouquan/MyDoc/Deep_Learning/My_TAOD/Train_Classification/models/PCB_Crop Resnet50_Pretrained 20240420_183406/200.pth"